[build]
  command = "set NODE_ENV=production && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"
